erDiagram

%% 자산 포트폴리오

  CUSTOMER {
      string id
      string name
      string email
  }
  ORDER {
      string id
      date orderDate
      string status
  }
  PRODUCT {
      string id
      string name
      float price
  }
  ORDER_ITEM {
      int quantity
      float price
  }
